# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Woodpecker Élagage
url: https://gct-wdpkr.github.io
baseurl: ""
logo: /assets/images/logo-circle.png
email: wdpecker.elagage@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
search: true

## Localization / i18n / Polyglot settings
languages: ["en", "fr"]
default_lang: fr
language_separator: "•" # "|", "•", "·", "-", "–"
exclude_from_localization: ["assets/css", "assets/images", "assets/js"]
parallel_localization: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default
repository: GCT-WDPKR/GCT-WDPKR.github.io
include:
  - _pages

## Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-polyglot
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from

## Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

## Exclude from processing
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

## YAML front matter settings
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: _posts/en
    values:
      lang: en
  - scope:
      path: _posts/fr
    values:
      lang: fr
  # _pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: _pages/en
    values:
      lang: en
  - scope:
      path: _pages/fr
    values:
      lang: fr
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Site customization
author:
  name: Geraint Thomas
  avatar: /assets/images/bio-photo.jpg
  bio:
    en: '"Arborist Pruner Climber" certified. Creator, and founder of Woodpecker Élagage.'
    fr: '"Arboriste Elagueur Grimpeur" certifié, createur, et patron de Woodpecker Élagage.'
  links:
    - label: Website
      icon: fas fa-fw fa-link
      url: https://gct-wdpkr.github.io/
    - label: Facebook
      icon: fab fa-fw fa-facebook
      url: https://www.facebook.com/woodpecker.elagage
    - label: Instagram
      icon: fab fa-fw fa-instagram
      url: https://www.instagram.com/woodpecker_elagage
    - label: Email
      icon: fas fa-fw fa-envelope
      url: mailto:wdpecker.elagage@gmail.com
    - label: Telephone
      icon: fas fa-fw fa-phone
      url: tel:0626794773

footer:
  links:
    - label: Facebook
      icon: fab fa-fw fa-facebook
      url: https://www.facebook.com/woodpecker.elagage
    - label: Instagram
      icon: fab fa-fw fa-instagram
      url: https://www.instagram.com/woodpecker_elagage
    - label: Email
      icon: fas fa-fw fa-envelope
      url: mailto:wdpecker.elagage@gmail.com
    - label: Telephone
      icon: fas fa-fw fa-phone
      url: tel:0626794773
