lang_name: "Français"
splash:
  title: "Woodpecker Élagage"
  excerpt: |
    Entreprise d’arboriste-élagueur-grimpeur. Certifié et assuré pour tout travail d’élagage et entretien des espaces verts.

    ! DEVIS GRATUIT !
  intro:
    - excerpt: "CONSEIL, ABATTAGE, DÉMONTAGE, RÉTENTION, REMISE EN SÉCURITÉ, TAILLE D'ÉCLAIRCIE, FRUCTIFICATION, BROYAGE, FENDAGE, ET ÉVACUATION DES DÉCHETS"
  feature_row:
    - image_path: /assets/images/realisation/aberttage-part-demontage/image-3.jpg
      alt: "Abattage par démontage"
      title: "Abattage par Démontage"
      excerpt: "Quand les contraintes autour oblige une approche plus délicate."
    - image_path: /assets/images/misc/IMG_20220819_114418_5.jpg
      # image_caption: "Image courtesy of [Unsplash](https://unsplash.com/)"
      alt: "Grand ou Petit"
      title: "Grand ou petit"
      excerpt: "Un service propre et précis n'importe la taille de l'arbre."
      url: "https://gct-wdpkr.github.io/realisations/"
      btn_label: "D'autres Réalisations"
      btn_class: "btn--primary"
    - image_path: /assets/images/realisation/IMG_20240418_150428_814.jpg
      title: "Travail en Rétention"
      excerpt: "Capables de s'attaquer aux travaux les plus difficiles, nous ne laissons rien au hasard. Faite confiance aux professionnels "
  feature_row2:
    - image_path: /assets/images/taille sanitaire.jpg
      alt: "Voici une taille d'eclaircie"
      title: "Voici une taille d'eclaircie"
      excerpt: "Envie de voir d'autres tailles possibles ? Suivez le lien dessous."
      url: "https://gct-wdpkr.github.io/services/"
      btn_label: "D'autres Services"
      btn_class: "btn--primary"
  feature_row3:
    - image_path: /assets/images/taille haie.jpg
      alt: "Taille d'Haie"
      title: "Taille d'Haie"
      excerpt: "Woodpecker Élagage, fait aussi de l'entretien de vos espaces verts. Prenez contact avec nous pour organiser un rendez-vous en suivant le lien dessous."
      url: "https://gct-wdpkr.github.io/contact/"
      btn_label: "Contactez nous"
      btn_class: "btn--primary"
  feature_row4:
    - image_path: /assets/images/fendeuse.jpg
      alt: "Fendage du Bois"
      title: "Fendage du Bois"
      excerpt: "Avec une puissance de 22 tonnes, rien ne résiste à notre bête de fendeuse. Suivez le lien dessous pour voir nos tarifs de location."
      url: "https://gct-wdpkr.github.io/services/"
      btn_label: "Tarifs de loacation"
      btn_class: "btn--primary"
