lang_name: "Français"
splash:
  title: "Woodpecker Élagage"
  excerpt: |
    Entreprise d’arboriste-élagueur-grimpeur. Certifié et assuré pour tout travail d’élagage et entretien des espaces verts.

    ! DEVIS GRATUIT !
  intro:
    - excerpt: "CONSEIL, ABATTAGE, DÉMONTAGE, RÉTENTION, REMISE EN SÉCURITÉ, TAILLE D'ÉCLAIRCIE, FRUCTIFICATION, BROYAGE, FENDAGE, ET ÉVACUATION DES DÉCHETS"
  feature_row:
    - image_path: assets/images/misc/IMG_20230812_114854_001.jpg
      alt: "FR placeholder image 1"
      title: "FR Placeholder 1"
      excerpt: "This is some sample content that goes here with **Markdown** formatting."
    - image_path: /assets/images/misc/IMG_20220819_114418_5.jpg
      # image_caption: "Image courtesy of [Unsplash](https://unsplash.com/)"
      alt: "FR placeholder image 2"
      title: "FR Placeholder 2"
      excerpt: "This is some sample content that goes here with **Markdown** formatting."
      url: "#test-link"
      btn_label: "Read More"
      btn_class: "btn--primary"
    - image_path: /assets/images/misc/IMG_20230421_102729_686.jpg
      title: "FR Placeholder 3"
      excerpt: "This is some sample content that goes here with **Markdown** formatting."
  feature_row2:
    - image_path: /assets/images/misc/IMG_20220819_114418_5.jpg
      alt: "FR placeholder image 2"
      title: "FR Placeholder Image Left Aligned"
      excerpt: 'This is some sample content that goes here with **Markdown** formatting. Left aligned with `type="left"`'
      url: "#test-link"
      btn_label: "Read More"
      btn_class: "btn--primary"
  feature_row3:
    - image_path: /assets/images/misc/IMG_20220819_114418_5.jpg
      alt: "FR placeholder image 2"
      title: "FR Placeholder Image Right Aligned"
      excerpt: 'This is some sample content that goes here with **Markdown** formatting. Right aligned with `type="right"`'
      url: "#test-link"
      btn_label: "Read More"
      btn_class: "btn--primary"
  feature_row4:
    - image_path: /assets/images/misc/IMG_20220819_114418_5.jpg
      alt: "FR placeholder image 2"
      title: "FR Placeholder Image Center Aligned"
      excerpt: 'This is some sample content that goes here with **Markdown** formatting. Centered with `type="center"`'
      url: "#test-link"
      btn_label: "Read More"
      btn_class: "btn--primary"