name: Build and deploy to gh-pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: write-all

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build with jekyll/builder
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chown jekyll:jekyll /srv/jekyll && jekyll build --future"
    - name: Copy CNAME to _site
      if: ${{ github.event_name == 'push' }}
      run: |
        sudo cp ${{ github.workspace }}/CNAME ${{ github.workspace }}/_site/CNAME
    - name: Deploy to gh-pages
      if: ${{ github.event_name == 'push' }}
      run: |
        sudo chown $( whoami ):$( whoami ) ${{ github.workspace }}/_site
        cd ${{ github.workspace }}/_site
        git init -b gh-pages
        git config user.name ${{ github.actor }}
        git config user.email ${{ github.actor }}@users.noreply.github.com
        git remote add origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git
        git add .
        git commit -m "Deploy site built from commit ${{ github.sha }}"
        git push -f -u origin gh-pages
